[tool.ruff]
target-version = "py311"
extend-exclude = [".venv"]
line-length = 100
show-fixes = true

[tool.ruff.lint]
# https://docs.astral.sh/ruff/rules/#error-e
select = ["ALL"]
ignore = [
  "ANN",     # flake8-annotations
  "D",       # pydocstyle
  "EM",      # flake8-errmsg
  "COM812",  # flake8-commas. Trailing comma missing
  "ISC001",  # flake8-implicit-str-concat. Checks for implicitly concatenated strings on a single line.
  "PLR2004", # pylint-refactor. Magic value used in comparison
  "TRY003",  # tryceratops. Avoid specifying long messages outside the exception class
  "TRY300",  # tryceratops. Consider moving this statement to an `else` block
]

[tool.ruff.lint.extend-per-file-ignores]
"test*" = [
  "FBT001",  # flake8-boolean-trap. Boolean-typed positional argument in function definition
  "PLR0913", # pylint-refactor. Too many arguments in function definition ({c_args} > {max_args})
  "S101",    # flake8-bandit. Use of assert detected
  "S105",    # flake8-bandit. Possible hardcoded password
  "S106",    # flake8-bandit. Possible hardcoded password
  "S107",    # flake8-bandit. Possible hardcoded password
  "SLF001",  # flake8-self. Private member accessed: {access}
]

[tool.ruff.lint.flake8-boolean-trap]
extend-allowed-calls = ["pydantic.Field"]

[tool.ruff.lint.flake8-builtins]
builtins-ignorelist = ["id"]

[tool.ruff.lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

[tool.ruff.lint.pylint]
allow-magic-value-types = ["int"]

[tool.ruff.lint.mccabe]
max-complexity = 8


[tool.mypy]
plugins = ["pydantic.mypy"]
follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true

# for strict mypy: (this is the tricky one :-))
disallow_untyped_defs = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = false
warn_required_dynamic_aliases = false


[tool.sqlfluff.core]
dialect = "postgres"
templater = "raw"
max_line_length = 120
verbose = 0
fix_even_unparsable = true

[tool.sqlfluff.indentation]
indent_unit = "space"
tab_space_size = 2
indented_joins = false
indented_using_on = true
template_blocks_indent = false

[tool.sqlfluff.templater]
unwrap_wrapped_queries = false

[tool.sqlfluff.rules.capitalisation.keywords]
capitalisation_policy = "upper"
